# Updated compose file pins image tags to published versions on Docker Hub
# and adds persistence + restart policies. Remove or adjust volumes as needed.
services:
    masternode:
        image: leodyversemilla07/multichain-master:2.3.3
        build: ./master
        stdin_open: true
        tty: true
        restart: unless-stopped
        healthcheck:
            # Use the bundled scripts/healthcheck_rpc.sh for robustness (avoids complex inline quoting)
            test: ["CMD", "/home/multichain/scripts/healthcheck_rpc.sh"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
        ports:
            - "7447:7447"   # Stable P2P / connect port
            - "8000:8000"   # RPC port (host access)
        environment:
            CHAIN_NAME: ${CHAIN_NAME}
            RPC_USER: ${RPC_USER}
            RPC_PASSWORD: ${RPC_PASSWORD}
            RPC_PASSWORD_FILE: /run/secrets/rpc_password
            RPC_ALLOWIP: ${RPC_ALLOWIP}
            VIRTUAL_HOST: multichain-master.docker
            VIRTUAL_PORT: 8000
        volumes:
            - master_data:/home/multichain/.multichain    # Persist chain data
            - ./scripts:/home/multichain/scripts:ro       # Helper scripts (read-only)
            - ./scripts:/scripts:ro                      # Convenience mount at /scripts
        secrets:
            - rpc_password
    explorer:
        image: leodyversemilla07/multichain-explorer:2.3.3
        build: ./explorer
        depends_on:
            masternode:
                condition: service_healthy
        stdin_open: true
        tty: true
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-fsS", "http://localhost:2750/"]
            interval: 45s
            timeout: 5s
            retries: 5
        ports:
            - "2750:2750"   # Explorer web UI
        environment:
            CHAIN_NAME: ${CHAIN_NAME}
            MASTER_PORT: ${MASTER_PORT}
            RPC_HOST: ${RPC_HOST}
            RPC_PORT: ${RPC_PORT}
            RPC_USER: ${RPC_USER}
            RPC_PASSWORD: ${RPC_PASSWORD}
            RPC_PASSWORD_FILE: /run/secrets/rpc_password
            PUBLIC_RPCHOST: ${PUBLIC_RPCHOST}
            RPC_ALLOWIP: ${RPC_ALLOWIP}
            VIRTUAL_HOST: multichain-explorer.docker
            VIRTUAL_PORT: 2750
        volumes:
            - master_data:/home/multichain/.multichain
        secrets:
            - rpc_password
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 512M

        # Service name resolution (masternode) replaces legacy links

    peer1:
        image: leodyversemilla07/multichain-node:2.3.3
        build: ./node
        depends_on:
            - masternode
        stdin_open: true
        tty: true
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "bash", "-c", "cd /home/multichain && HOME=/home/multichain multichain-cli $${CHAIN_NAME:-dockerchain} getinfo >/dev/null 2>&1"]
            interval: 45s
            timeout: 5s
            retries: 5
        environment:
            CHAIN_NAME: ${CHAIN_NAME}
            MASTER_PORT: ${MASTER_PORT}
        volumes:
            - peer1_data:/home/multichain/.multichain
            - ./scripts:/scripts:ro
            - ./scripts:/home/multichain/scripts:ro
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 384M

    peer2:
        image: leodyversemilla07/multichain-node:2.3.3
        build: ./node
        depends_on:
            - masternode
        stdin_open: true
        tty: true
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "bash", "-c", "cd /home/multichain && HOME=/home/multichain multichain-cli $${CHAIN_NAME:-dockerchain} getinfo >/dev/null 2>&1"]
            interval: 45s
            timeout: 5s
            retries: 5
        environment:
            CHAIN_NAME: ${CHAIN_NAME}
            MASTER_PORT: ${MASTER_PORT}
        volumes:
            - peer2_data:/home/multichain/.multichain
            - ./scripts:/scripts:ro
            - ./scripts:/home/multichain/scripts:ro
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 384M

volumes:
    master_data:
    peer1_data:
    peer2_data:

secrets:
    rpc_password:
        file: ./secrets/rpc_password.txt