name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: |
          shellcheck base/*.sh master/*.sh node/*.sh explorer/*.sh scripts/*.sh || true
          # Report but don't fail (convert to strict later)
  smoke-test:
    runs-on: ubuntu-latest
    needs: shellcheck
    services:
      docker:
        image: docker:dind
        privileged: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build images (local tags)
        run: |
          docker build -t local/multichain-base:ci ./base
          docker build -t local/multichain-master:ci --build-arg MULTICHAIN_BASE_VERSION=2.3.3 master
          docker build -t local/multichain-node:ci --build-arg MULTICHAIN_BASE_VERSION=2.3.3 -f node/Dockerfile .
          docker build -t local/multichain-explorer:ci explorer
      - name: Adjust compose file to use local tags
        run: |
          cp docker-compose.yaml docker-compose.ci.yaml
          sed -i 's#leodyversemilla07/multichain-master:2.3.3#local/multichain-master:ci#g' docker-compose.ci.yaml
          sed -i 's#leodyversemilla07/multichain-node:2.3.3#local/multichain-node:ci#g' docker-compose.ci.yaml
          sed -i 's#leodyversemilla07/multichain-explorer:master#local/multichain-explorer:ci#g' docker-compose.ci.yaml
      - name: Run smoke test
        run: |
          export COMPOSE_FILE=docker-compose.ci.yaml
          bash scripts/smoke-test.sh
