name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images with Docker Compose
        run: |
          docker compose build --parallel

      - name: Start services
        run: |
          docker compose up -d

      - name: Run smoke test
        run: |
          chmod +x ./scripts/smoke-test.sh || true
          ./scripts/smoke-test.sh

      - name: Tear down
        if: always()
        run: docker compose down -v
